package easyjob.pojo;

// Generated 30/11/2016 5:54:21 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Records generated by hbm2java
 */
public class Records implements java.io.Serializable {
	private static final long serialVersionUID = -6270183348852371688L;
	private int id;
	private String companyName;
	private String position;
	private String description;
	private Date releaseDate;
	private String appliedMethod;
	private Date appliedDate;
	private Boolean requireManualProcess;

	public Records() {
	}

	public Records(int id) {
		this.id = id;
	}

	public Records(int id, String companyName, String position,
			String description, Date releaseDate, String appliedMethod,
			Date appliedDate, Boolean requireManualProcess) {
		this.id = id;
		this.companyName = companyName;
		this.position = position;
		this.description = description;
		this.releaseDate = releaseDate;
		this.appliedMethod = appliedMethod;
		this.appliedDate = appliedDate;
		this.requireManualProcess = requireManualProcess;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	public String getAppliedMethod() {
		return this.appliedMethod;
	}

	public void setAppliedMethod(String appliedMethod) {
		this.appliedMethod = appliedMethod;
	}

	public Date getAppliedDate() {
		return this.appliedDate;
	}

	public void setAppliedDate(Date appliedDate) {
		this.appliedDate = appliedDate;
	}

	public Boolean getRequireManualProcess() {
		return this.requireManualProcess;
	}

	public void setRequireManualProcess(Boolean requireManualProcess) {
		this.requireManualProcess = requireManualProcess;
	}

}
